server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:
      timeout: 5000ms
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（负数表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池中的最小空闲连接
          min-idle: 10
          # 空闲连接检测周期
          time-between-eviction-runs: 60s


jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6  # 秘钥，32位随机字符
  expires-in: 120 # 令牌过期时间，单位秒,这里是为了测试方便，设置得较短，2分钟

logging:
  level:
    top.dwy.filter_interceptor.filter.RateLimitFilter: DEBUG